openapi: 3.0.3
info:
  title: Foodie Supreme
  version: 1.0.0
  description: Web application that works with checks and print them
paths:
  /api/meal-checks/:
    post:
      operationId: meal_checks_create
      description: "\n        Create order.\n        1. order_id: It`s unique value\
        \ for investigate customer.\n        2. order_details: Describes what the\
        \ customer ordered, as well as the price of the order.\n        3. point_id:\
        \ Order location  \n        "
      tags:
      - meal-checks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
components:
  schemas:
    Order:
      type: object
      properties:
        order_id:
          type: integer
        order_details:
          type: string
        point_id:
          type: integer
      required:
      - order_details
      - order_id
      - point_id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
