# Generated by Django 4.2 on 2023-07-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("api_key", models.CharField(blank=True, max_length=128, unique=True)),
                (
                    "check_type",
                    models.CharField(
                        choices=[("KITCHEN", "Kitchen"), ("CLIENT", "Client")],
                        max_length=10,
                    ),
                ),
                ("point_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("KITCHEN", "Kitchen"), ("CLIENT", "Client")],
                        max_length=10,
                    ),
                ),
                ("order", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("RENDERED", "Rendered"),
                            ("PRINTED", "Printed"),
                        ],
                        default="NEW",
                        max_length=10,
                    ),
                ),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "printer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meal_checks.printer",
                    ),
                ),
            ],
        ),
    ]
