# Generated by Django 4.2 on 2023-07-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_checks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="api_key",
            field=models.CharField(blank=True, max_length=130, unique=True),
        ),
    ]
