# Generated by Django 4.2 on 2023-07-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_checks", "0002_alter_printer_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdf/"),
        ),
    ]
